### ISSUE TITLE
BUG: La CPU puede colocar dos barcos que se intercepten

### ISSUE THREAD

**Issue by santiagoolivos** [Benjale/Testing-P1#18]
Al jugar en modo Single Player la Cpu puso a dos barcos que se interceptan, por lo que vencí a los dos barcos de en cuatro targets en vez de 6. No se debería permitir que la CPU coloque dos barcos que se intercepten

![WhatsApp Image 2022-04-21 at 12 27 12 PM](https://user-images.githubusercontent.com/62115136/164568886-bc7afd9c-e11b-417d-b8ee-1dfcbf719a90.jpeg)

**Comment by Benjale** [comment]
El BUG fue solucionado en la siguiente issue 
https://github.com/Benjale/Testing-P1/commit/cd1142a7dbcff5bca85f09a27bd6d5cee541f1cf
