### ISSUE TITLE
BUG: La CPU se cae atacando

### ISSUE THREAD

**Issue by raimundoloeser** [Benjale/Testing-P1#21]
La CPU se esta cayendo al no ingresar un input de buena manera, se desconoce de donde viene el error todavia

<img width="1007" alt="Captura de Pantalla 2022-04-24 a la(s) 23 12 39" src="https://user-images.githubusercontent.com/53836400/165014677-ca5cda26-b62d-46ef-8277-9b935cbc8942.png">

<img width="904" alt="Captura de Pantalla 2022-04-24 a la(s) 22 57 17" src="https://user-images.githubusercontent.com/53836400/165014623-e803f20d-718d-4952-b056-714cef25f3eb.png">

**Comment by raimundoloeser** [comment]
Se idetificó que el error es con los lugares donde ha atacado, algo esta fallando ya que no reconoció un ataque anterior

<img width="498" alt="Captura de Pantalla 2022-04-24 a la(s) 23 36 03" src="https://user-images.githubusercontent.com/53836400/165016754-3a798c15-8782-48a7-a861-c41fdcede2fa.png">

**Comment by raimundoloeser** [comment]
La llamada recursiva esta fallando
<img width="351" alt="Captura de Pantalla 2022-04-24 a la(s) 23 57 24" src="https://user-images.githubusercontent.com/53836400/165018440-b1154b7a-526b-4e82-b740-b823e844ed7a.png">

<img width="1075" alt="Captura de Pantalla 2022-04-24 a la(s) 23 56 05" src="https://user-images.githubusercontent.com/53836400/165018386-a6fcf5cf-db2b-47b2-9091-79dfb1f06012.png">

**Comment by raimundoloeser** [comment]
Solucionado en el commit [17af553](https://github.com/Benjale/Testing-P1/commit/17af55334320d2bfb74dc3661802af59245956ae)

**Comment by Benjale** [comment]
Para testear esta solución se creo una función que simula el *random_pos* llamada *random_pos_test* para poder otorgarles coordenadas al disparo de la IA. De tal manera, podíamos revisar que si la CPU ya disparó en una posición e intenta disparar de nuevo en esa posición, se llamará a otro random hasta obtener una coordenada no usada. El commit en que se subió el test es el siguiente:  https://github.com/Benjale/Testing-P1/commit/590baf9c1882a2f1bc6ed500eec694e9f141c9dc

**Comment by Benjale** [comment]
Además en el siguiente commit se realizaron arreglos de sintaxis del test llamado *test_two_shots_in_one_place* https://github.com/Benjale/Testing-P1/commit/b240875f4591b9f0de251ade29079eeb21a2019b
