### ISSUE TITLE
BUG: La CPU ataca afuera del tablero de juego

### ISSUE THREAD

**Issue by raimundoloeser** [Benjale/Testing-P1#22]
La CPU puede atacar a posiciones que estén fuera del del tablero, ya que si el jugador pon un bote que contenga un posición (x, 15) y la CPU le achunta a la 15 como primer tiro, luego intentará con el 16 ya que entra al primer if que se puede ver en la imagen. Al fin y al cabo, solo se filtra el tablero de nivel fácil
<img width="666" alt="Captura de Pantalla 2022-04-25 a la(s) 00 33 00" src="https://user-images.githubusercontent.com/53836400/165021387-85d31e72-ff4b-4ff6-a0cc-1179a83d569e.png">

**Comment by raimundoloeser** [comment]
Solucionado en el commit [https://github.com/Benjale/Testing-P1/commit/17af55334320d2bfb74dc3661802af59245956ae](17af553)

**Comment by santiagoolivos** [comment]
Adicional al commit anterior, se creo el siguiente commit 5cd819a2c5c1fe0f608f890c2069d46f3a86734a . En este se presentan los cambios para testear la solución a esta Issue..

**Comment by santiagoolivos** [comment]
Este problema fue solucionado y testeado en el commit b240875f4591b9f0de251ade29079eeb21a2019b
