### ISSUE TITLE
BUG: CPU no termina de jugar

### ISSUE THREAD

**Issue by raimundoloeser** [Benjale/Testing-P1#23]
Al parecer no se estan descontando bien los barcos hundidos en la cpu

**Comment by raimundoloeser** [comment]
No se incluía el la notificacion de disparo en la clase boat.

<img width="407" alt="Captura de Pantalla 2022-04-25 a la(s) 00 54 39" src="https://user-images.githubusercontent.com/53836400/165023196-5df4c952-aaa7-4b09-93ea-3f25bb3dcfbc.png">

**Comment by Benjale** [comment]
El error fue solucionado en el siguiente commit: https://github.com/Benjale/Testing-P1/commit/5ab761546ef165ae425f93b68e171ce424e8eac0

**Comment by Benjale** [comment]
El test que demuestra que el Bug fue solucionado se subió mediante el siguiente commit: https://github.com/Benjale/Testing-P1/commit/9bc76ee7215f6c83a9e974a696dbd1ec1ff7a400
